name: build nix packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        package: [ putricide, rp-utils, folkevognen, homepage, sketch-bot, lavalink, tools.wallpaper, tools.banner ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build system
        run: nix build .#${{ matrix.package }}
